# Generated by Django 4.2.3 on 2024-01-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train_dataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=1000)),
                ("answers", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
